apiVersion: db.zeabix.com/v1alpha1
kind: Database
metadata:
  labels:
    app.kubernetes.io/name: database
    app.kubernetes.io/instance: database-sample
    app.kubernetes.io/part-of: db-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: db-operator
  name: database-sample
spec:
  mysqlServerRef: mysqlserver-sample
  username: profileapp
  secretRef: profile-service-cred
