apiVersion: db.zeabix.com/v1alpha1
kind: MySQLServer
metadata:
  labels:
    app.kubernetes.io/name: mysqlserver
    app.kubernetes.io/instance: mysqlserver-sample
    app.kubernetes.io/part-of: db-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: db-operator
  name: mysqlserver-sample
spec:
  host: mysql-server:3306
  secretRef: mysql-cred
